version: "3.7"

services:
  db:
    image: postgres
    container_name: mydb
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    networks:
      - mydjango

  django-docker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-docker
    networks:
      - "mydjango"
    volumes:
      - /home/regis/gh/my/django-docker/myproject/:/app/myproject/
    ports:
      - "8000:8000"
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

networks:
  mydjango:
